# Python Lambda

In [ ]:
def add(a,b):
  return a+b

In [ ]:
add(5,7)

In [ ]:
add = lambda a,b: a+b

In [ ]:
add(5,7)

In [ ]:
add(10,25)

In [ ]:
def distance(x1, y1, x2, y2):
  return ( (x1-x2)**2 + (y1-y2)**2 )**.5

In [ ]:
new_distance = lambda x1, y1, x2, y2: ( (x1-x2)**2 + (y1-y2)**2 )**.5

In [ ]:
distance(5,6,10,20)

In [ ]:
new_distance(5,6,10,20)

# Python Variable Scope

In [ ]:
def print_name(name):
  name = "Asif"
  print(f'My name is {name}')

name = "Iqbal"
print_name(name)
print(f'My name is {name}')

In [ ]:
def grade(number):
  a = 100
  b = 20
  c = 12
  print(a)
  if number>=100:
    number = 80
    print(f'The number is {number}')
    return number

  if number<=33:
    number = 33
    print(f'The number is {number}')
    return number

  print(f'The number is {number}')
  return number

In [ ]:
number = 120
new_number = grade(number)

print(f'You got {number}, but the final number is {new_number}')

In [ ]:
a = 10

def print_a():
  a = 20
  print(f'The value of a inside the function is {a}')

print_a()
print(f'The value of a outside the function is {a}')

# Python Classes/Objects


### Classes:

###### Definition: A class in Python is a blueprint for creating objects. It defines a datatype by encapsulating the attributes and behaviors (methods) that the objects created from the class can perform.
###### Components: A class typically includes:
<br>
Attributes: Variables that store data specific to the class.
<br>
Methods: Functions that define behaviors of the class.

### Objects:

###### Definition: An object is an instance of a class. When a class is defined, no memory is allocated until an object of that class is created.
###### Creation: Objects are created by calling the class itself as if it were a function. This triggers the class's __init__ method, which initializes the object.
###### Usage: Objects access the attributes and methods of the class they were created from, allowing for individual object data and behaviors as defined by the class.

### __init__() Function
###### Purpose: The __init__() method is the constructor in Python. It's automatically invoked when a new object of a class is created.
###### Self Parameter: The first parameter of the __init__() method is self, which is a reference to the current instance of the class. It allows access to the attributes and methods of the class in Python.
###### Initialization: The __init__() method is used to initialize the attributes of an object. This method can take additional arguments to set the initial state of a new object.

In [1]:
class animal:
  legs = 0
  mammal = False
  bark = "------"
  is_pet = False

  def barks(self):
    print(self.bark)

  def pet(self):
    if self.is_pet == True:
      print("The animal is suitable for petting")
    else:
      print("The animal is not suitable for petting")

In [2]:
cat = animal

In [6]:
cat.legs

0

In [4]:
cat.mammal

False

In [7]:
class animal:

  def __init__(self, p_legs, p_mammal, p_bark, p_is_pet):
    self.legs = p_legs
    self.mammal = p_mammal
    self.bark = p_bark
    self.is_pet = p_is_pet

  def barks(self):
    print(self.bark)

  def pet(self):
    if self.is_pet == True:
      print("The animal is suitable for petting")
    else:
      print("The animal is not suitable for petting")

In [8]:
cat = animal(4, True, "Mhew Mhew", True)

In [11]:
cat.pet()

The animal is suitable for petting


In [12]:
class animal:

  def __init__(self, p_legs, p_mammal, p_bark, p_is_pet, fur, aggresive):
    self.legs = p_legs
    self.mammal = p_mammal
    self.bark = p_bark
    self.is_pet = p_is_pet
    self.fur = fur
    self.aggresive = aggresive

  def aggresive(self):
    print(self.aggresive)

  def barks(self):
    print(self.bark)

  def pet(self):
    if self.is_pet == True:
      print("The animal is suitable for petting")
    else:
      print("The animal is not suitable for petting")

In [13]:
cat = animal(4, True, "Mew Mew", True, True, False)

cow = animal(4, True, "Hamba Hamba", False, True, False)

eagle = animal(2, False, "----", False, True, True)


# cat.barks()

In [14]:
cow.legs

4

In [15]:
eagle.legs

2

In [16]:
cat.barks()

Mew Mew


In [17]:
cat.pet()

The animal is suitable for petting


In [26]:
class animal:

  def __init__(self, p_legs, p_mammal, p_bark, p_is_pet):
    self.legs = p_legs
    self.mammal = p_mammal
    self.bark = p_bark
    self.is_pet = p_is_pet

  def barks(self):
    print(self.bark)
    return 0

  def pet(self):
    if self.is_pet == True:
      print("The animal is suitable for petting")
    else:
      print("The animal is not suitable for petting")
    return 0

In [27]:
cat = animal(4, True, "Mew Mew", True)

In [28]:
print(cat.legs, cat.mammal, cat.barks(), cat.pet())

Mew Mew
The animal is suitable for petting
4 True 0 0


# Python RegEx


### Metacharacters
<li>
[] ->	A set of characters <br>
. ->	Any character (except newline character) <br>
^ ->	Starts with <br>
$ ->	Ends with <br>
* ->	Zero or more occurrences <br>
+ ->	One or more occurrences <br>
? ->	Zero or one occurrences <br>
{} ->	Exactly the specified number of occurrences <br>
</li>

# Try .. Except

In [29]:
print("This is before try--except")


print("Hello World")
print(1/0)
print("This is python programming class.")

print("This is after try--except")

This is before try--except
Hello World


ZeroDivisionError: division by zero

In [37]:
print("This is before try--except")

try:
  print("Hello World")
  print(1/0)
  print("This is python programming class.")
except:
  print("Warning!!! Don't divide by 0")

print("This is after try--except")

This is before try--except
Hello World
This is python programming class.
This is after try--except


In [36]:
car = ['Ford', "Fiat", "Audi"]

try:
  print(car[1])
except:
  print("Please check the index of the list")

Fiat


### try Block:
<li>
Purpose: This is where you place the code that might cause an exception during execution. The Python interpreter checks the code in this block for any errors.
</li>

### except Block:
<li>
Handling Exceptions: If an exception occurs in the try block, Python stops the execution of that block and transfers control to the except block. You can specify particular exceptions to catch or handle all exceptions generically.
</li>
<li>
Multiple Exceptions: You can have multiple except clauses to handle different exceptions in different ways.
</li>

### else Block:
<li>
No Exceptions: This block is executed if no exceptions were raised in the try block. It’s often used for code that should run if the try block was successful.
</li>
<li>
Placement: It must be placed after all except blocks.
</li>

### finally Block:
<li>
Always Executes: This block runs regardless of whether an exception was raised or not and whether it was caught if raised. It's typically used for clean-up actions, such as closing files or releasing resources.
</li>
<li>
Guaranteed Execution: Even if the program crashes or a return statement is encountered in the try or except blocks, the finally block will still execute.
</li>

### We can use try..except for multiple error.

In [39]:
car = ['Ford', "Fiat", "Audi"]

try:
  divide = 1/0
  print(car[3])
except:
  print("Please check the index of the list")

Please check the index of the list


In [40]:
car = ['Ford', "Fiat", "Audi"]
print(car[3])

IndexError: list index out of range

In [41]:
1/0

ZeroDivisionError: division by zero

In [50]:
car = ['Ford', "Fiat", "Audi"]

try:
  divide = 1/0
  print(car[3])
except ZeroDivisionError:
  print("Don't divide by zero")
except IndexError:
  print("Please check the index of the list")
except:
  print("We are facing some Error")

Don't divide by zero


In [45]:
car = ['Ford', "Fiat", "Audi"]

try:
  print(car[3])
  divide = 1/0
except ZeroDivisionError:
  print("Don't divide by zero")
except IndexError:
  print("Please check the index of the list")
finally:
  print("This will always print in the try..except block")

Please check the index of the list
This will always print in the try..except block


# Read Documentation

In [52]:
help(dict)

Help on class dict in module builtins:

class dict(object)
 |  dict() -> new empty dictionary
 |  dict(mapping) -> new dictionary initialized from a mapping object's
 |      (key, value) pairs
 |  dict(iterable) -> new dictionary initialized as if via:
 |      d = {}
 |      for k, v in iterable:
 |          d[k] = v
 |  dict(**kwargs) -> new dictionary initialized with the name=value pairs
 |      in the keyword argument list.  For example:  dict(one=1, two=2)
 |  
 |  Built-in subclasses:
 |      StgDict
 |  
 |  Methods defined here:
 |  
 |  __contains__(self, key, /)
 |      True if the dictionary has the specified key, else False.
 |  
 |  __delitem__(self, key, /)
 |      Delete self[key].
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  __getitem__(...)
 |      x.__getitem__(y) <==> x[y]
 |  
 |  __gt__(self, value, /)
 |  

### ** Please learn the following concept by yourself.**
(Out of scope for this course)

1. Inheritance
2. Polymorphism
3. Iterators
4. File Handling
5. IO File

# Install package

In [53]:
pip install numpy

In [54]:
pip install pandas

# Python Numpy
NumPy (Numerical Python) is an open source Python library that’s used in almost every field of science and engineering.

It’s the universal standard for working with numerical data in Python.


In [58]:
import numpy

In [59]:
import numpy as np

In [60]:
a = np.array([1,2,3]) # 1 Dimensional array

In [61]:
type(a)

numpy.ndarray

In [62]:
a

array([1, 2, 3])

In [63]:
b = np.array( [ [1,2,3], [4,5,6] ])  # 2 Dimensional array

In [65]:
print(b)

[[1 2 3]
 [4 5 6]]


In [66]:
a.shape

(3,)

In [67]:
b.shape

(2, 3)

In [74]:
c = np.array([ [  [1,2,3], [4,5,6]  ], [   [7,8,9], [10,11,12]  ] ])

In [75]:
c.shape

(2, 2, 3)

In [93]:
d = np.array([ [  [1,2,3], [4,5,6]  ], [   [7,8,9], [10,11,12]  ], [ [13,14,15], [16,17,18] ] ])

In [94]:
d.shape

(3, 2, 3)

In [77]:
print(a)
print("######")
print(b)
print("######")
print(c)

[1 2 3]
######
[[1 2 3]
 [4 5 6]]
######
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [79]:
a[1]

2

In [81]:
b[1][1]

5

In [88]:
c[1][0][2]

9

In [90]:
print(a)
print("######")
print(b)
print("######")
print(c)

[1 2 3]
######
[[1 2 3]
 [4 5 6]]
######
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [89]:
len(a)

3

In [91]:
len(b)

2

In [92]:
len(c)

2

### What’s the difference between a Python list and a NumPy array?

###### NumPy gives you an enormous range of fast and efficient ways of creating arrays and manipulating numerical data inside them.

###### While a Python list can contain different data types within a single list, all of the elements in a NumPy array should be homogeneous.

###### The mathematical operations that are meant to be performed on arrays would be extremely inefficient if the arrays weren’t homogeneous.

###### NumPy arrays are faster and more compact than Python lists. NumPy uses much less memory to store data and it provides a mechanism of specifying the data types. This allows the code to be optimized even further.

###### 1D Matrix / column Matrix

In [103]:
a = np.array([1,2,3])

###### 2D Matrix

In [117]:
b = np.array( [ [1,2,3], [4,5,6] ])

###### 3D Matrix

In [105]:
c = np.array([ [  [1,2,3]  ,   [4,5,6] ], [[7,8,9], [10,11,12]] ])

### More concepts

In [102]:
b = np.array( [ [1,2,3], [4,5] ])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [99]:
c = np.array([ [ [1,2,3] , [4,5,6] ], [ [7,8,9] ] ])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

### Indexing and Slicing

In [106]:
print(a)
print("######")
print(b)
print("######")
print(c)

[1 2 3]
######
[[1 2 3]
 [4 5 6]]
######
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [107]:
b[1]

array([4, 5, 6])

In [108]:
c[0][0][2]

3

In [109]:
print(b)

[[1 2 3]
 [4 5 6]]


In [110]:
b[0][1] = 100

In [111]:
print(b)

[[  1 100   3]
 [  4   5   6]]


In [112]:
b[1][1] = 1000

In [113]:
print(b)

[[   1  100    3]
 [   4 1000    6]]


### Shape and Size of an ndarray

In [118]:
print(a)
print("######")
print(b)
print("######")
print(c)

[1 2 3]
######
[[1 2 3]
 [4 5 6]]
######
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [114]:
a.shape

(3,)

In [116]:
a.size

3

In [119]:
b.shape

(2, 3)

In [120]:
b.size

6

In [121]:
c.size

12

### Create a matrix
###### with zeros, ones, arange

In [125]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [126]:
zero = np.zeros( [2,3] )

In [128]:
print(zero)

[[0. 0. 0.]
 [0. 0. 0.]]


In [129]:
zero[1][2] = 100

print(zero)

[[  0.   0.   0.]
 [  0.   0. 100.]]


In [133]:
one = np.ones([3,3,3])
print(one)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


In [131]:
one[1][0][2] = 100

In [132]:
print(one)

[[[  1.   1.   1.]
  [  1.   1.   1.]
  [  1.   1.   1.]]

 [[  1.   1. 100.]
  [  1.   1.   1.]
  [  1.   1.   1.]]

 [[  1.   1.   1.]
  [  1.   1.   1.]
  [  1.   1.   1.]]]


In [137]:
a = np.array([ [1,2,3], [1,2,3], [1,2,3], [1,2,3], [1,2,3], [1,2,3], [1,2,3], [1,2,3], [1,2,3], [1,2,3] ])

a.shape

(10, 3)

In [140]:
np.arange(100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

### Adding, removing, and sorting elements

In [142]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

c = np.concatenate( (a, b) )

print(c)

[1 2 3 4 5 6 7 8]


In [143]:
type(c)

numpy.ndarray

###### But you need to think about the "axis" sometime

In [146]:
a = np.array([ [1, 2], [3, 4] ])  # 2D numpy Array
b = np.array([   [5, 6]   ])      # 2D numpy array

print(a.shape)
print(b.shape)

(2, 2)
(1, 2)


In [149]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])

np.concatenate( (a, b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [150]:
a1 = np.array([[1,2], [3,4]])
a2 = np.array([[5,6], [7,8]])

In [153]:
np.concatenate((a1, a2), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [155]:
np.vstack((a1,a2))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [154]:
np.concatenate((a1, a2), axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [156]:
np.hstack((a1,a2))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [160]:
a = np.array([1000,2, 10, 200, 5])

In [161]:
a = np.sort(a)

In [159]:
print(a)

[   2    5   10  200 1000]


In [162]:
reverse_array = a[::-1]
print(reverse_array)

[1000  200   10    5    2]


In [163]:
a = np.sort(a)[::-1]
print(a)

[1000  200   10    5    2]


### Reshape an ndarray

In [164]:
a = np.array([1,2,3,4,5,6])
a.shape

(6,)

In [165]:
b = a.reshape(2,3)
print(b)

[[1 2 3]
 [4 5 6]]


In [166]:
c = a.reshape(3,2)
print(c)

[[1 2]
 [3 4]
 [5 6]]


In [169]:
a = np.array([1,2,3,4,5])
a.shape

(5,)

In [170]:
d = a.reshape(2,3)

ValueError: cannot reshape array of size 5 into shape (2,3)

In [172]:
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
a.shape

(12,)

In [173]:
e = a.reshape(2,2,3)
print(e)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [180]:
c = np.array([ [  [1,2,3], [4,5,6]   ], [   [7,8,9], [10,11,12]   ] ])

In [181]:
c.shape

(2, 2, 3)

In [182]:
x = c.reshape(4,3)
x.shape

(4, 3)

In [183]:
x

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [184]:
x = c.reshape(6,2)
x

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

### Flatten an ndarray

In [185]:
c = np.array([ [[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]] ])
c.shape

(2, 2, 3)

In [186]:
x = c.flatten()
print(x)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [187]:
type(x)

numpy.ndarray

### Creating array from existing data

In [188]:
### [2:5]  -> [2,3,4]

a = np.array([1,2,3,4,5,6])
b = a[2:5]
print(b)

[3 4 5]


In [189]:
type(b)

numpy.ndarray

### Basic array operations

In [191]:
a = np.array([1,2])
b = np.array([2,3])

In [192]:
a+b

array([3, 5])

In [193]:
a*b

array([2, 6])

In [194]:
a/b

array([0.5       , 0.66666667])

In [196]:
a+10

array([11, 12])

In [197]:
a *10

array([10, 20])

In [198]:
d = b/3

In [199]:
print(d)

[0.66666667 1.        ]


In [200]:
np.round(d,2)

array([0.67, 1.  ])

### Max/Min/Sum

In [201]:
a = np.array([1,2,3,4,5])

In [202]:
a.max()

5

In [203]:
a.min()

1

In [204]:
a.sum()

15

In [206]:
c = np.array([ [[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]] ])

In [207]:
c.max()

12

In [208]:
c.min()

1

In [209]:
c.sum()

78

# Pandas

In [ ]:
pip install pandas

In [ ]:
import pandas as pd

### Series: a one-dimensional labeled array holding data of any type,
such as integers, strings, Python objects etc.

### DataFrame: a two-dimensional data structure that holds data like a two-dimension array or a table with rows and columns.

### Object creation

In [ ]:
s = pd.Series([0, 1, 3, 5, np.nan, 6, 8])

In [ ]:
print(s)

In [ ]:
print(type(s))

In [ ]:
import pandas as pd

calories = {"day1": 420, "day2": 380, "day3": 390}

myvar = pd.Series(calories)

print(myvar)

In [ ]:
print(type(myvar))

In [ ]:
import pandas as pd

data = {
  "Weight": [80,77, 65, 73, 90],
  "Height": [176, 182, 156, 172, 167],
  'Age': [20,30,35, 25, 37]
}

#load data into a DataFrame object:
df = pd.DataFrame(data)

print(df)

In [ ]:
print(type(df))

In [ ]:
import pandas as pd

data = {
  "Weight": [80, 77, 65, 73, 90],
  "Height": [176, 182, 156, 172, 167]
}

#load data into a DataFrame object:
df = pd.DataFrame(data, index = ["Person1", "Person2", "Person3", "Person4", "Person5"])

print(df)

### Pandas Dataframe is a collection of Series

In [ ]:
df

In [ ]:
print(type(df["Weight"]))

### Pandas Slicing

In [ ]:
import pandas as pd

data = {
  "Weight": [80, 77, 65, 73, 90],
  "Height": [176, 182, 156, 172, 167]
}

#load data into a DataFrame object:
df = pd.DataFrame(data, index = ["Person1", "Person2", "Person3", "Person4", "Person5"])

print(df)

In [ ]:
df["Weight"]

In [ ]:
print(df.loc['Person1'])

In [ ]:
print(df.iloc[0])

In [ ]:
print(df.iloc[[0,2]])

In [ ]:
import pandas as pd

data = {
  "Weight": [80, 77, 65, 73, 90],
  "Height": [176, 182, 156, 172, 167]
}

#load data into a DataFrame object:
df = pd.DataFrame(data, index = ["Person1", "Person2", "Person3", "Person4", "Person5"])

print(df)

In [ ]:
print(df.loc["Person2"])

In [ ]:
print(df.iloc[0:3])

### Reading a csv file

In [ ]:
# df = pd.read_excel("/content/Bank_Loans_dataset.xlsx")

In [ ]:
df = pd.read_csv("/content/Bank_Loans_dataset.csv")

In [ ]:
df

In [ ]:
df.shape

In [ ]:
df.head()

In [ ]:
df.tail()

In [ ]:
df.columns

In [ ]:
df.shape

In [ ]:
df.head()

In [ ]:
df.info()

In [ ]:
df.dtypes

### Changing Data type

In [ ]:
# loan_id:
df['loan_id'] = df['loan_id'].astype('object')
# repaid:
df['repaid'] = df['repaid'].astype('category')

In [ ]:
# loan_start:
df['loan_start'] = pd.to_datetime(df['loan_start'])
# loan_end:
df['loan_end'] = pd.to_datetime(df['loan_end'], format = '%Y-%m-%d')

### Pandas Slicing

### In columns

### in rows

### Replacing values

### Let's check the missing value

###### Replace the missing value with a value/mean/meadina/mode

In [1]:
import pandas as pd

df = pd.read_csv('/content/Bank_Loans_dataset.csv')

x = df["loan_amount"].mean()
# x = df["loan_amount"].median()
# x = df["loan_amount"].mode()[0]

df["loan_amount"].fillna(x, inplace = True)

FileNotFoundError: [Errno 2] No such file or directory: '/content/Bank_Loans_dataset.csv'

### Correlation

# Matplotlib

In [ ]:
import matplotlib.pyplot as plt

plt.plot([1, 2, 4, 7, 4, 2, 1])
plt.show() # You must call plt.show() to render your final plot.

In [ ]:
import matplotlib.pyplot as plt

plt.plot([-3, -2, 5, 0], [1, 6, 4, 3])
plt.show()

In [ ]:
import matplotlib.pyplot as plt
import numpy as np

x = np.array([1, 2])
y = np.array([3, 4])
plt.scatter(x, y, color=["r","b"]) # Read more on the color argument in the examples section below.
plt.show()

In [ ]:
import matplotlib.pyplot as plt

plt.plot([-3, -2, 5, 0], [1, 6, 4, 3])
plt.axis([-4, 6, 0, 7])
plt.show()

In [ ]:
import matplotlib.pyplot as plt
import numpy as np

x = np.linspace(-2, 2, 50)
plt.plot(x, x**2, "r--", label="Square function")
plt.plot(x, x**3, "g-", label="Cube function")
plt.legend(loc="best")
plt.grid(True)
plt.show()

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

x = np.linspace(-2, 2, 50)
plt.plot(x, x**2, "r--", label="Square function")

# Add a legend
plt.legend(['Square plot'], fontsize=7)

# Set X and Y Labels
plt.xlabel('x', fontsize=12)
plt.ylabel('x^2', fontsize=12)

# Add a plot title
plt.title('Square function', fontsize=15)

plt.grid(True)
plt.show()

In [ ]:
import matplotlib.pyplot as plt
import numpy as np

x = np.linspace(-2.0, 2.0, 30)

plt.subplot(2, 2, 1) # 2 rows, 2 columns, 1st subplot = top left
plt.plot(x, x)
plt.subplot(2, 2, 2) # 2 rows, 2 columns, 2nd subplot = top right
plt.plot(x, x**2)
plt.subplot(2, 2, 3) # 2 rows, 2 columns, 3rd subplot = bottow left
plt.plot(x, x**3)
plt.subplot(2, 2, 4) # 2 rows, 2 columns, 4th subplot = bottom right
plt.plot(x, x**4)
plt.show()

In [ ]:
import matplotlib.pyplot as plt
import numpy as np

plt.subplot(2, 2, 1)  # 2 rows, 2 columns, 1st subplot = top left
plt.plot(x, x)
plt.subplot(2, 2, 2)  # 2 rows, 2 columns, 2nd subplot = top right
plt.plot(x, x**2)
plt.subplot(2, 1, 2)  # 2 rows, *1* column, 2nd subplot = bottom
plt.plot(x, x**3)
plt.show()

# Plot with Pandas and Matplotlib

### With Pandas

In [ ]:
import pandas as pd

df = pd.read_csv("/content/stroke.csv")
df.head()

In [ ]:
df.columns

In [ ]:
df.plot(kind='scatter', x = "age", y = "heart_disease", title="Scatter Plot")

In [ ]:
df.plot(kind='scatter', x = "age", y = "bmi", title="Scatter Plot")

In [ ]:
df.plot(kind='scatter', x = "age", y = "stroke", title="Scatter Plot")

### With Matplotlib

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
df = pd.read_csv("/content/bank.csv", sep=';')
df.head()

In [ ]:
plt.plot(df['balance'])
plt.show()

In [ ]:
plt.plot(df['balance'])
plt.xlabel('Customer')
plt.ylabel('Balance')
plt.title('Customer Balance')
plt.legend()
plt.show()

In [ ]:
plt.hist(df['balance'])
plt.ylabel('Customer')
plt.xlabel('Balance')
plt.title('Customer Balance Distribution')
plt.show()

In [ ]:
plt.bar(data['marital'], df['balance'])
plt.xlabel('Marital Status')
plt.ylabel('Balance')
plt.title('Customer Balance Distribution')
plt.show()

In [ ]:
plt.bar(data['housing'], df['balance'])
plt.xlabel('Housing')
plt.ylabel('Balance')
plt.title('Customer Balance Distribution')
plt.show()

In [ ]:
plt.scatter(data['age'], data['balance'])
plt.show()

In [ ]:
plt.scatter(data['age'], data['balance'])
plt.xlabel('Age')
plt.ylabel('Balance')
plt.title("Balance by Age")
plt.show()

In [ ]:
plt.pie(data['marital'].value_counts())
plt.show()

In [ ]:
plt.pie(data['marital'].value_counts(), labels = data['marital'].value_counts().keys())
plt.legend()
plt.show()